[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$Repo,
  [string]$OutFile = "State.md"
)

$ErrorActionPreference = "Stop"

function Get-IssuesJson {
  param([string]$Repo)
  gh issue list --repo $Repo --state all --limit 500 --json number,title,state,labels,assignees,body,url | ConvertFrom-Json
}

function Get-PrsJson {
  param([string]$Repo)
  gh pr list --repo $Repo --state all --limit 200 --json number,title,state,headRefName,author,url,statusCheckRollup | ConvertFrom-Json
}

$issues = Get-IssuesJson -Repo $Repo
$prs    = Get-PrsJson -Repo $Repo

$open      = @($issues | Where-Object { $_.state -eq "OPEN" })
$inprog    = @($open | Where-Object { ($_.labels.name) -contains "in-progress" })
$review    = @($open | Where-Object { ($_.labels.name) -contains "review" })
$blocked   = @($open | Where-Object { ($_.labels.name) -contains "blocked" })

$openPrs   = @($prs | Where-Object { $_.state -eq "OPEN" })

$lines = @()
$lines += "# State - $Repo"
$lines += ""
$lines += "**Generated:** $(Get-Date -Format o)"
$lines += "**Source:** GitHub (regenerated by ``scripts/rebuild-state.ps1``)"
$lines += "**Do not edit by hand.**"
$lines += ""
$lines += "## Summary"
$lines += ""
$lines += "- Open issues: $($open.Count) | in-progress: $($inprog.Count) | review: $($review.Count) | blocked: $($blocked.Count)"
$lines += "- Open PRs: $($openPrs.Count)"
$lines += ""

$phases = $open | ForEach-Object {
  $p = ($_.labels.name | Where-Object { $_ -like "phase:*" } | Select-Object -First 1)
  if (-not $p) { $p = "phase:unassigned" }
  [pscustomobject]@{ Phase = $p; Issue = $_ }
} | Group-Object Phase | Sort-Object Name

foreach ($g in $phases) {
  $lines += "## $($g.Name)"
  $lines += ""
  $lines += "| # | Title | Status labels | Assignee |"
  $lines += "|---|---|---|---|"
  foreach ($row in $g.Group) {
    $i = $row.Issue
    $statusLabels = ($i.labels.name | Where-Object { $_ -in "in-progress","review","blocked","ready" }) -join ", "
    $assignee = ($i.assignees.login -join ", ")
    $lines += "| #$($i.number) | $($i.title) | $statusLabels | $assignee |"
  }
  $lines += ""
}

if ($openPrs.Count -gt 0) {
  $lines += "## Open PRs"
  $lines += ""
  $lines += "| PR | Title | Branch | Author |"
  $lines += "|---|---|---|---|"
  foreach ($pr in $openPrs) {
    $lines += "| #$($pr.number) | $($pr.title) | $($pr.headRefName) | $($pr.author.login) |"
  }
  $lines += ""
}

if ($blocked.Count -gt 0) {
  $lines += "## Blocked"
  $lines += ""
  foreach ($b in $blocked) {
    $lines += "- #$($b.number) $($b.title) - $($b.url)"
  }
  $lines += ""
}

$lines -join "`n" | Out-File -FilePath $OutFile -Encoding utf8
Write-Information "Wrote $OutFile ($($lines.Count) lines)" -InformationAction Continue
